mv Figure1-microbiome.pdf microbiome.pdf
mv Figure1-microbiome.png microbiome.png
mv Figure1-microbiome.svg microbiome.svg
mv Figure2-brain.pdf brain.pdf
mv Figure2-brain.png brain.png
mv Figure2-brain.svg brain.svg
mv Figure3-lipids.pdf lipids.pdf
mv Figure3-lipids.png lipids.png
mv Figure3-lipids.svg lipids.svg
mv Figure4-ai.pdf ai.pdf
mv Figure4-ai.png ai.png
mv Figure4-ai.svg ai.svg
mv Figure5-network.pdf network.pdf
mv Figure5-network.png network.png
mv Figure5-network.svg network.svg
mv FigureS1-eeg.png eeg.png
mv FigureS1-variance.pdf variance.pdf
mv FigureS1-variance.png variance.png
mv FigureS1-variance.svg variance.svg
mv FigureS2-eeg.pdf eeg.pdf
mv FigureS2-eeg.png eeg.png
mv FigureS2-eeg.svg eeg.svg
mv FigureS3-beta.pdf beta.pdf
mv FigureS3-beta.png beta.png
mv FigureS3-beta.svg beta.svg
mv FigureS4-covariates.pdf covariates.pdf
mv FigureS4-covariates.png covariates.png
mv FigureS4-covariates.svg covariates.svg
mv FigureS5-rda.pdf rda.pdf
mv FigureS5-rda.png rda.png
mv FigureS5-rda.svg rda.svg
